services:
  backend:
    build: ./Back-End
    ports:
      - 8082:8082
    env_file: ./Back-End/database/.env  
    volumes:
      - ./Back-End:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - "./Back-End/sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - mysql_data:/var/lib/mysql  # ← Volumen persistente

volumes:
  mysql_data:  # ← Declaración del volumen
